In [1]:
import pandas as pd

In [12]:
# 78% in memory phew that was scary. 
sample_train_unbalanced_df = pd.read_csv('../data/samples/sample_train_unbalanced.csv',
                                         sep='\t',
                                         header=None,
                                         names=["label", "comment", "author", "subreddit", "score", "ups", "downs", "date", "created_utc", "parent_comment"])

In [13]:
import nltk
from nltk.corpus import stopwords
import string

In [41]:
# First, clean up our stopwords and punctuation

# https://stackoverflow.com/questions/17390326/getting-rid-of-stop-words-and-document-tokenization-using-nltk
stop = stopwords.words('english') + list(string.punctuation)
stop_set = set(stop)

def clean_stopwords_and_punctuation(comment_col, col_name):
    comment = str(comment_col[col_name])
    return ' '.join([word for word in nltk.word_tokenize(comment.lower()) if word not in stop_set])

In [26]:
# TODOs: We should have a countvectorizer for complete frequencies
# We should also use tf-idf since I feel like that'll get us better results.
sample_train_unbalanced_df.head()[['comment']]

                                             comment
0                                    A Lizard Person
1             Check this out... SAUL ALINSKY LUCIFER
2                                  Dat google search
3      The American people will take notice of this.
4  I was thinking seeds, but now you have me worr...

In [29]:
sample_train_unbalanced_df[['comment']] = sample_train_unbalanced_df[['comment']].apply(lambda x: clean_stopwords_and_punctuation(x, 'comment'), axis=1)

In [36]:
sample_train_unbalanced_df.head(20)[['comment']]

                                              comment
0                                       lizard person
1                      check ... saul alinsky lucifer
2                                   dat google search
3                         american people take notice
4                          thinking seeds worried lol
5              favorite `` 're gone 'll go mad^1 '' 1
6   standard answer `` marvel characters men tryin...
7                             always make mistake ...
8                                            n't tell
9   said `` 540 burn '' bill attempted take dick h...
10  given fact companies host debates profit campa...
11                                                yes
12                       's beauty ... n't understand
13  well chicago nasl sounds like fan fiction poin...
14                     would bo1 much better game w w
15                                          1,473,463
16                                          1,473,489
17                                          1,478,665
18                                              124bf
19                                          1,478,793

In [37]:
sample_train_unbalanced_df.head(20)

,label,comment,author,subreddit,score,ups,downs,date,created_utc,parent_comment
0,0,lizard person,N9neRhymes,The_Donald,4,-1,-1,2016-11,1478221360,What is Hillary Clinton
1,0,check ... saul alinsky lucifer,N9neRhymes,The_Donald,12,-1,-1,2016-11,1480434930,"Like, maybe 5 or 6 right now, my dude"
2,0,dat google search,N9neRhymes,The_Donald,1,-1,-1,2016-10,1476297087,Have y'all heard Green Day's new album??
3,0,american people take notice,N9neRhymes,The_Donald,11,-1,-1,2016-10,1476563305,Hillary Clinton avoiding every single schedule...
4,0,thinking seeds worried lol,ruthannr94,femalefashionadvice,1,1,0,2016-09,1472852595,Your growing conditions sound ideal for a fall...
5,0,favorite `` 're gone 'll go mad^1 '' 1,ME24601,hamiltonmusical,17,-1,-1,2016-11,1480351020,My favorite of Lin's annotations from the Hami...
6,0,standard answer `` marvel characters men tryin...,ME24601,comicbooks,27,-1,-1,2016-12,1482013682,What are the fundamental differences between M...
7,0,always make mistake ...,ME24601,TopMindsOfReddit,13,-1,-1,2016-12,1483076552,"Just for future reference, it's ""cuckold,"" not..."
8,0,n't tell,ME24601,movies,1,1,0,2016-09,1473106947,Stop all the hating! Just share great scenes...
9,0,said `` 540 burn '' bill attempted take dick h...,ME24601,politics,1,1,0,2016-09,1474311611,Hillary Clinton Says Youth Causes Will Be 'Pas...
10,0,given fact companies host debates profit campa...,ME24601,politics,1,-1,-1,2016-10,1476924836,"Missing From the Debates: Climate Change, Pove..."
11,0,yes,ME24601,AmericanHorrorStory,2,-1,-1,2016-10,1477535559,Was that Rory in the tree?
12,0,'s beauty ... n't understand,sawillis,MLS,14,-1,-1,2016-12,1480800092,Martinos time in both Barca and Argentina were...
13,0,well chicago nasl sounds like fan fiction poin...,sawillis,MLS,6,-1,-1,2016-12,1481648855,"that's their twitter account handle, that's ho..."
14,0,would bo1 much better game w w,baseballv10,Infinitewarfare,1,-1,-1,2016-11,1478015603,"It'll be WaW if anything, not BO1."
15,0,"1,473,463",davidjl123,counting,2,-1,-1,2016-11,1477959554,"1,473,462"
16,0,"1,473,489",davidjl123,counting,2,-1,-1,2016-11,1477959604,"1,473,488"
17,0,"1,478,665",davidjl123,counting,2,-1,-1,2016-11,1478175760,1 478 664
18,0,124bf,davidjl123,counting,2,-1,-1,2016-11,1478178434,124BE
19,0,"1,478,793",davidjl123,counting,2,-1,-1,2016-11,1478181547,"1,478,792"

In [38]:
sample_train_unbalanced_df.to_csv('../data/samples/sample_train_main_comment_unbalanced_cleaned.csv', sep='\t', index=False)

In [ ]:
sample_train_unbalanced_df[['parent_comment']] = sample_train_unbalanced_df[['parent_comment']].apply(lambda x: clean_stopwords_and_punctuation(x, 'parent_comment'), axis=1)

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [35]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(sample_train_unbalanced_df['comment'])

In [ ]:
count_vectorizer = CountVectorizer()
count_matrix = count_vectorizer.fit_transform(sample_train_unbalanced_df['comment'])